# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b779f635f2c574030937af3cf67410e3b06d2c66eaf9d2bd2b3f1644daa13940e8f0a5c842e6a24dc96d37da55d62cbdd84a158582ca2f9feb6e0a1a86271a65

test:
  secret_key_base: 3d3bb4b35a0a799a5276163cacdecf2babdae5c481d65ff6e439f14bbc880e473500e6f67873dbd12c5bad2c82b8010d61130fa48fc1104bcdf8578898b7ed25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
